# -----------------------------
# BASIC CONFIG
# -----------------------------
spring.application.name=API-GATEWAY
server.port=8083

# -----------------------------
# SERVICE DISCOVERY (EUREKA)
# -----------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Better instance visibility
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
#spring.main.web-application-type=reactive
# -----------------------------
# GATEWAY ROUTES (ACTIVE)
# -----------------------------

# USER SERVICE (runs on 8080)
spring.cloud.gateway.routes[0].id=USERSERVICE
spring.cloud.gateway.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# HOTEL SERVICE (runs on 8081)
spring.cloud.gateway.routes[1].id=HOTELSERVICE
spring.cloud.gateway.routes[1].uri=lb://HOTELSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/hotels/**
#spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# RATING SERVICE (runs on 8082)
spring.cloud.gateway.routes[2].id=RATINGSERVICE
spring.cloud.gateway.routes[2].uri=lb://RATINGSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/ratings/**
#spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# -----------------------------
# OPTIONAL (AUTO ROUTING - DEV ONLY)
# -----------------------------
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=false

# -----------------------------
# GLOBAL CORS (FOR FRONTEND)
# -----------------------------
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PUT,DELETE
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# -----------------------------
# TIMEOUTS
# -----------------------------
#spring.cloud.gateway.httpclient.connect-timeout=5000
#spring.cloud.gateway.httpclient.response-timeout=5s

# -----------------------------
# LOGGING (DEBUG DURING DEV)
# -----------------------------
#logging.level.org.springframework.cloud.gateway=INFO
#logging.level.reactor.netty.http.client=INFO

# -----------------------------
# ACTUATOR
# -----------------------------
#management.endpoints.web.exposure.include=*
#management.endpoint.gateway.enabled=true
#management.endpoint.health.show-details=always