spring.application.name=ratingService
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/ms_ratingDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=ms_ratingDB_user
spring.datasource.password=0408@ms_ratingDB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensure data.sql runs after Hibernate initializes the schema
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true