spring.application.name=serviceRegistery

# Server configuration
server.port=8761

# Eureka instance
eureka.instance.hostname=localhost

# Eureka client behavior (since this is server)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false